var shopName = "stonegas";
console.log(shopName);
var oven_container = 3;
console.log(oven_container);
var isGasAppliances = true;
console.log(isGasAppliances);
var userName = "haya";
console.log(userName);
var age = 4;
console.log(age);
var isStudent = false;
console.log(isStudent);
